/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/ConfirmDialog/index.vue')['default']
    InnerLink: typeof import('./src/components/InnerLink/index.vue')['default']
    LinkDialog: typeof import('./src/components/Tiptap/components/LinkDialog.vue')['default']
    LoadingDialog: typeof import('./src/components/LoadingDialog/index.vue')['default']
    ParentView: typeof import('./src/components/ParentView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectImage: typeof import('./src/components/Tiptap/components/SelectImage.vue')['default']
    Tiptap: typeof import('./src/components/Tiptap/index.vue')['default']
    ViewLoading: typeof import('./src/components/ViewLoading/index.vue')['default']
  }
}
