/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/backend/': RouteRecordInfo<'/backend/', '/backend', Record<never, never>, Record<never, never>>,
    '/backend/demo/rabbit/': RouteRecordInfo<'/backend/demo/rabbit/', '/backend/demo/rabbit', Record<never, never>, Record<never, never>>,
    '/backend/demo/socket/': RouteRecordInfo<'/backend/demo/socket/', '/backend/demo/socket', Record<never, never>, Record<never, never>>,
    '/backend/sys/dict/': RouteRecordInfo<'/backend/sys/dict/', '/backend/sys/dict', Record<never, never>, Record<never, never>>,
    '/backend/sys/dict/data': RouteRecordInfo<'/backend/sys/dict/data', '/backend/sys/dict/data', Record<never, never>, Record<never, never>>,
    '/backend/sys/menu/': RouteRecordInfo<'/backend/sys/menu/', '/backend/sys/menu', Record<never, never>, Record<never, never>>,
    '/backend/sys/role/': RouteRecordInfo<'/backend/sys/role/', '/backend/sys/role', Record<never, never>, Record<never, never>>,
    '/backend/sys/role/authUser': RouteRecordInfo<'/backend/sys/role/authUser', '/backend/sys/role/authUser', Record<never, never>, Record<never, never>>,
    '/backend/sys/user/': RouteRecordInfo<'/backend/sys/user/', '/backend/sys/user', Record<never, never>, Record<never, never>>,
    '/backend/sys/user/authRole': RouteRecordInfo<'/backend/sys/user/authRole', '/backend/sys/user/authRole', Record<never, never>, Record<never, never>>,
    '/backend/tool/json/': RouteRecordInfo<'/backend/tool/json/', '/backend/tool/json', Record<never, never>, Record<never, never>>,
    '/backend/tool/tiptap/': RouteRecordInfo<'/backend/tool/tiptap/', '/backend/tool/tiptap', Record<never, never>, Record<never, never>>,
    '/error/401': RouteRecordInfo<'/error/401', '/error/401', Record<never, never>, Record<never, never>>,
    '/error/404': RouteRecordInfo<'/error/404', '/error/404', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }
}
